version: '3'
services:
  ops-db:
    image: avidito/puska-ops-db:1.0
    environment:
      - POSTGRES_USER=${OPS_DB_USER:-puska}
      - POSTGRES_PASSWORD=${OPS_DB_PASSWORD:-puska}
      - POSTGRES_DB=${OPS_DB_NAME:-puska}
    ports:
      - 5600:5432
    volumes:
      - puska-ops-db:/var/lib/postgresql/data

  dwh-db:
    image: avidito/puska-dwh-db:1.0
    environment:
      - POSTGRES_USER=${DWH_DB_USER:-puska}
      - POSTGRES_PASSWORD=${DWH_DB_PASSWORD:-puska}
      - POSTGRES_DB=${DWH_DB_NAME:-puska}
    ports:
      - 5601:5432
    volumes:
      - puska-dwh-db:/var/lib/postgresql/data
  
  etl-batch:
    image: avidito/puska-etl-batch:1.0
    environment:
      - DWH_DB_HOSTNAME=${DWH_DB_HOSTNAME:-dwh-db}
      - DWH_DB_PORT=${DWH_DB_PORT:-5432}
      - DWH_DB_NAME=${DWH_DB_NAME:-puska}
      - DWH_DB_USER=${DWH_DB_USER:-puska}
      - DWH_DB_PASSWORD=${DWH_DB_PASSWORD:-puska}
      - OPS_DB_HOSTNAME=${OPS_DB_HOSTNAME:-ops-db}
      - OPS_DB_PORT=${OPS_DB_PORT:-5432}
      - OPS_DB_NAME=${OPS_DB_NAME:-puska}
      - OPS_DB_USER=${OPS_DB_USER:-puska}
      - OPS_DB_PASSWORD=${OPS_DB_PASSWORD:-puska}
    entrypoint: ["sleep", "infinity"]
    volumes:
      - ./services/etl-batch/etl:/scripts/etl
volumes:
  puska-ops-db:
  puska-dwh-db: