version: '3'
services:
  db-ops:
    image: avidito/puska-ops-db:1.0-postgres15.3
    build:
      context: ./services/db-ops
    environment:
      - POSTGRES_USER=${OPS_DB_USER:-puska}
      - POSTGRES_PASSWORD=${OPS_DB_PASSWORD:-puska}
      - POSTGRES_DB=${OPS_DB_NAME:-puska}
    ports:
      - 5600:5432
    volumes:
      - puska-db-ops:/var/lib/postgresql/data
volumes:
  puska-db-ops: