version: '3'
services:
  db-ops:
    image: avidito/puska-ops-db:1.0-postgres15.3
    # build:
    #   context: ./services/db-ops
    environment:
      - POSTGRES_USER=${OPS_DB_USER:-puska}
      - POSTGRES_PASSWORD=${OPS_DB_PASSWORD:-puska}
      - POSTGRES_DB=${OPS_DB_NAME:-puska}
    ports:
      - 5600:5432
    volumes:
      - puska-db-ops:/var/lib/postgresql/data

  db-dwh:
    image: avidito/puska-db-dwh:1.0-postgres15.3
    # build:
    #   context: ./services/db-dwh
    environment:
      - POSTGRES_USER=${DWH_DB_USER:-puska}
      - POSTGRES_PASSWORD=${DWH_DB_PASSWORD:-puska}
      - POSTGRES_DB=${DWH_DB_NAME:-puska}
    ports:
      - 5601:5432
    volumes:
      - puska-db-dwh:/var/lib/postgresql/data
  
  etl-batch:
    image: avidito/puska-etl-batch:1.0-beam2.52.0
    # build:
    #   context: ./services/etl-batch
    environment:
      - DWH_DB_HOSTNAME=${DWH_DB_HOSTNAME:-db-dwh}
      - DWH_DB_PORT=${DWH_DB_PORT:-5432}
      - DWH_DB_NAME=${DWH_DB_NAME:-puska}
      - DWH_DB_USER=${DWH_DB_USER:-puska}
      - DWH_DB_PASSWORD=${DWH_DB_PASSWORD:-puska}
      - OPS_DB_HOSTNAME=${OPS_DB_HOSTNAME:-db-ops}
      - OPS_DB_PORT=${OPS_DB_PORT:-5432}
      - OPS_DB_NAME=${OPS_DB_NAME:-puska}
      - OPS_DB_USER=${OPS_DB_USER:-puska}
      - OPS_DB_PASSWORD=${OPS_DB_PASSWORD:-puska}
    entrypoint: ["sleep", "infinity"]
    volumes:
      - ./services/etl-batch/etl:/scripts/etl
volumes:
  puska-db-ops:
  puska-db-dwh: